include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: info
    unused_import: error
    unused_local_variable: error
    missing_required_param: error
    always_use_package_imports: error
    directives_ordering: error
    unawaited_futures: error
    invalid_assignment: error
    missing_return: error
    dead_code: error
    cast_nullable_to_non_nullable: error
