name: serial_task_executor
description: A Dart package providing a simple and efficient way to execute tasks serially.
version: 0.0.1
repository: https://github.com/DartAndrik/serial_task_executor
issue_tracker: https://github.com/DartAndrik/serial_task_executor/issues

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9
